### ISSUE TITLE
G DOC FORMAT

### ISSUE THREAD

**Issue by DHANDAPANISATTANATHAN** [SSOMENSREPO/G-DOC-FORMAT#1]
<h2>G DOC FORMAT

**DURATION 4 DAYS
TASK OWNER: PUNI**

Check the below folder.Read the **Document Formatting Specifications.doc**

https://drive.google.com/drive/folders/0B0KangOyYg_pMGQ5R1BmSFV5R2s/0B_f0d7mdbV_USmdteHFucHQ4azQ/0B0KangOyYg_pfnFOTkt0YW5rWF9lRThNY1hjZlJGamctTXVjVEdWby1JdS02MV9sZkoxanM/0B0KangOyYg_pfjh3MVVoblAtTDNHTjB3c002eUF0c0tpQjNrN1ZFZUtXY2NCbm4wNG4tTFU/0B0Y3ZlxivXEUfnFXb2FUVXlMTzAxV083Zy1FcU83d0M5My1LS2c1QWhOS25lQ2pEak1tWjg

**Comment by punithavimalraj** [comment]
https://github.com/SSOMENSREPO/G-DOC-FORMAT/releases/tag/v1.0
