### ISSUE TITLE
G DOC ISSUE

### ISSUE THREAD

**Issue by DHANDAPANISATTANATHAN** [SSOMENSREPO/G-DOC-FORMAT#2]
**DEFECT OWNER:PUNI**

Tested v 2.0 and found the below issues

1.DRIVE NOT DEFINED
ReferenceError: "Drive" is not defined.
While uploading file i got this error.

2.Some time isert text msg in side bar showing inserting...
but log : Cannot call method "getElement" of null. 

refer the below log

https://docs.google.com/spreadsheets/d/1sog5KBNip0LdZHaMuWQ-Rj7zy6fFjRTuGzhUwgRTCwA/edit#gid=2032713932

**Comment by punithavimalraj** [comment]
point 1- Drive API shld enable through Resources- Advanced google services inside script
point 2-https://github.com/SSOMENSREPO/G-DOC-FORMAT/releases/tag/v3.0
